---
abstract: 'MATT DAEMON'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Matt-Daemon
no_index:
  directory:
    - inc
    - t
requires:
  Log::Syslog::Abstract: 0
  Proc::Daemon: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/acme-matt-daemon/tree/master
version: 0.01
